# Bind ResourceGroup viewer role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kro-viewers
subjects:
- kind: Group
  name: viewers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kro-viewer
  apiGroup: rbac.authorization.k8s.io
---
# Bind WebApplication admin role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapplication-admins
  namespace: default
subjects:
- kind: Group
  name: app-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: webapplication-admin
  apiGroup: rbac.authorization.k8s.io 