apiVersion: kro.run/v1alpha1
kind: GatewayConfig
metadata:
  name: main-gateway
  namespace: kro
spec:
  name: main-gateway
  hostname: "gateway.internal.dev.azure.com"
  tlsSecretName: tls-certificate
  tlsSecretNamespace: kro 