apiVersion: v1
kind: Secret
metadata:
  name: logging-law-credentials
  namespace: logging
type: Opaque
stringData:
  {{ ansible_operator_meta.namespace }}-{{ ansible_operator_meta.name }}.conf: |
    [OUTPUT]
      Name            azure
      Match           processed.law-endpoint.{{ ansible_operator_meta.namespace }}.{{ ansible_operator_meta.name }}.*
      Customer_ID     {{ law.workspace_id }}
      Shared_Key      {{ user_token }}
      Log_Type        {{ law.table }} 