apiVersion: kro.run/v1alpha1
kind: Logging
metadata:
  name: logging
  namespace: logging
spec:
  name: logging-collector
  endpointType: law
  law:
    workspaceId: "your-workspace-id"  # Replace with actual workspace ID
    token: "your-token"               # Replace with actual token
    table: mylawtable
    