apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: gitrepo
  namespace: kro
spec:
  schema:
    apiVersion: v1alpha1
    kind: GitRepo
    spec:
      swci: string | required=true description="SWCI identifier"
      openvironment: string | required=true description="Environment name"
      suffix: string | required=true description="Namespace suffix"
      namespacename: string | required=true description="Name of the namespace"
      resourcequotacpu: string | default="1" description="CPU resource quota"
      resourcequotamemorygb: string | default="1" description="Memory resource quota in GB"
      resourcequotastoragegb: string | default="10Gi" description="Storage resource quota"
      branchname: string | required=true description="Git branch name"
      gitlabrepourl: string | required=true description="GitLab repository URL"

    status:
      ready: ${namespace.metadata.name != ""}

  resources:
    - id: namespace
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.swci}-${schema.spec.openvironment}-${schema.spec.suffix}

    - id: networkpolicy
      template:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-${schema.spec.swci}
          namespace: ${schema.spec.swci}-${schema.spec.openvironment}-${schema.spec.suffix}
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
          ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  namespace: ${schema.spec.swci}
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: aks-istio-ingress
            - namespaceSelector:
                matchLabels:
                  kubernetes.azure.com/managedby: aks

    - id: resourcequota
      template:
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: resource-quota
          namespace: ${schema.spec.swci}-${schema.spec.openvironment}-${schema.spec.suffix}
        spec:
          hard:
            requests.cpu: "${schema.spec.resourcequotacpu}"
            requests.memory: "${schema.spec.resourcequotamemorygb}Gi"
            requests.storage: "${schema.spec.resourcequotastoragegb}"

    - id: peerauthentication
      template:
        apiVersion: security.istio.io/v1beta1
        kind: PeerAuthentication
        metadata:
          name: ${schema.spec.namespacename}-mtls-policy
          namespace: ${schema.spec.swci}-${schema.spec.openvironment}-${schema.spec.suffix}
          labels:
            component: mesh
        spec:
          mtls:
            mode: STRICT

    - id: gitrepository
      template:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: GitRepository
        metadata:
          name: ${schema.spec.namespacename}-repo
          namespace: ${schema.spec.namespacename}
        spec:
          interval: 5m0s
          ref:
            branch: ${schema.spec.branchname}
          secretRef:
            name: cluster-config-auth
          timeout: 1m0s
          url: ${schema.spec.gitlabrepourl}

    - id: externalsecret
      template:
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        metadata:
          name: cluster-config-auth
          namespace: ${schema.spec.namespacename}
        spec:
          refreshInterval: 10m
          secretStoreRef:
            kind: ClusterSecretStore
            name: gitops-appteam-sharedvault
          target:
            name: cluster-config-auth
            creationPolicy: Merge
          data:
            - secretKey: password
              remoteRef:
                key: readonly-pattoken-gitlab
                decodingStrategy: Auto

    - id: secret
      template:
        kind: Secret
        metadata:
          name: cluster-config-auth
          namespace: ${schema.spec.namespacename}
        apiVersion: v1
        data:
          username:
          ca.crt: 