apiVersion: kro.run/v1alpha1
kind: StorageConfig
metadata:
  name: storage
  namespace: kro
spec:
  name: test-storage
  namespace: kro
  storageAccount: krostorage
  secretName: storage-secret
  shareName: testshare,testsahre2,testshare3
  storageSize: "10Gi" 