apiVersion: kro.run/v1alpha1
kind: WhiskyAppProd
metadata:
  name: whiskyapp-prod
  namespace: kro
spec:
  name: whiskyapp-prod
  image: nginx:1.25.3
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"